version: '3.8'

services:
  web:
    build:
      context: ../Crepe-Tuna-Docker
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
    volumes:
      - .:/app
      - pip_cache:/root/.cache/pip

volumes:
  pip_cache:
    name: pip_cache